/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import db.DBconnect;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;




public class AdminDentist extends javax.swing.JFrame {
    
    
    public void loadDentistSchedule() {
    try {
        DefaultTableModel dtm = (DefaultTableModel) jtable2.getModel();
        dtm.setRowCount(0); // Clear existing rows
        
        Connection con = DBconnect.getConnection();
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery("SELECT * FROM dentist");
        
        while (rs.next()) {
            Object[] row = {
                rs.getString("work_date"),
                rs.getString("doctor_name"),
                rs.getString("start_time"),
                rs.getString("end_time")
            };
            dtm.addRow(row);
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error loading data: " + e.getMessage());
    }
}

    
    private final String url = "jdbc:mysql://localhost:3306/dental_clinic_db";
    private final String user = "root";
    private final String password = "";
    
    public AdminDentist() {
        initComponents();
        loadDentistDetails();
        loadDentistSchedule();
    }
    
    public void loadDentistDetails() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); 

        String sql = "SELECT name, contact_no, address, email FROM dentist_details";

        try (Connection conn = DriverManager.getConnection(url, user, password);
             PreparedStatement pstmt = conn.prepareStatement(sql);
             ResultSet rs = pstmt.executeQuery()) {

            while (rs.next()) {
                String name = rs.getString("name");
                String contact = rs.getString("contact_no");
                String address = rs.getString("address");
                String email = rs.getString("email");

                
                model.addRow(new Object[]{name, contact, address, email});
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Data Load Error: " + ex.getMessage());
        }
    }
    
    private void clearFields() {
        DName.setText("");
        DNo.setText("");
        Daddress.setText("");
        DEmail.setText("");
        DPassword.setText("");
        ReDPassword.setText("");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        DName = new javax.swing.JTextField();
        DNo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        DEmail = new javax.swing.JTextField();
        Daddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CreateDAccountBtn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        DPassword = new javax.swing.JPasswordField();
        ReDPassword = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        deleteBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        searchtxt = new javax.swing.JTextField();
        Searchbtn1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtable2 = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Home");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 230, 50));

        jPanel4.setBackground(new java.awt.Color(0, 153, 204));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Dentist Dashboard");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(50, 50, 50))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jPanel5.setBackground(new java.awt.Color(0, 102, 153));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Patient Dashboard");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(50, 50, 50))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 776));

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel4.setText("Name");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));
        jPanel2.add(DName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 190, -1));
        jPanel2.add(DNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, 190, -1));

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel5.setText("Contact No:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel6.setText("Email");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, -1, -1));
        jPanel2.add(DEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, 190, -1));
        jPanel2.add(Daddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 190, -1));

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel7.setText("Password");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

        jLabel8.setFont(new java.awt.Font("Poppins", 1, 13)); // NOI18N
        jLabel8.setText("Dentist Schedule Manage");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, -1, -1));

        CreateDAccountBtn.setBackground(new java.awt.Color(0, 102, 153));
        CreateDAccountBtn.setForeground(new java.awt.Color(255, 255, 255));
        CreateDAccountBtn.setText("Create Account");
        CreateDAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateDAccountBtnActionPerformed(evt);
            }
        });
        jPanel2.add(CreateDAccountBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 120, 130, 40));

        jPanel6.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 770, 10));

        jPanel7.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel9.setText("Address");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));
        jPanel2.add(DPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 190, -1));
        jPanel2.add(ReDPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, 190, -1));

        jLabel10.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel10.setText("Re-enter Password");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Contact No", "Address", "Email"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jScrollPane1.setViewportView(jScrollPane2);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 730, 130));

        deleteBtn.setBackground(new java.awt.Color(204, 204, 204));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel2.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 420, 150, 40));

        editBtn.setBackground(new java.awt.Color(204, 204, 204));
        editBtn.setText("Edit Data");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });
        jPanel2.add(editBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, 150, 40));

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        jPanel2.add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 240, 100, -1));
        jPanel2.add(searchtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 240, 380, -1));

        Searchbtn1.setText("Search");
        Searchbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Searchbtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(Searchbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, 100, -1));

        jtable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Dentist", "Start Time", "End Time"
            }
        ));
        jScrollPane4.setViewportView(jtable2);

        jScrollPane3.setViewportView(jScrollPane4);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 540, 720, 150));

        jPanel8.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, -1, -1));

        jLabel11.setFont(new java.awt.Font("Poppins", 1, 13)); // NOI18N
        jLabel11.setText("Create Dentist Account");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jLabel12.setFont(new java.awt.Font("Poppins", 1, 13)); // NOI18N
        jLabel12.setText("Dentist Data manage");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        jButton1.setText("Approve");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 700, 100, 40));

        jButton2.setText("Remove");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 700, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1057, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        AdminHome home = new AdminHome();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        AdminPatient patient = new AdminPatient();
        patient.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void CreateDAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateDAccountBtnActionPerformed
        String name = DName.getText().trim();
    String contactNo = DNo.getText().trim();
    String address = Daddress.getText().trim();
    String email = DEmail.getText().trim();
    String password = new String(DPassword.getPassword());
    String rePassword = new String(ReDPassword.getPassword());
    
    if (name.isEmpty() || contactNo.isEmpty() || address.isEmpty() || email.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all fields.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!password.equals(rePassword)) {
        JOptionPane.showMessageDialog(this, "Passwords do not match!", "Password Mismatch", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    String sql = "INSERT INTO dentist_details (name, contact_no, address, email, password) VALUES (?, ?, ?, ?, ?)";
    
    try (Connection conn = DBconnect.getConnection();
         PreparedStatement pstmt = conn.prepareStatement(sql)) {

        pstmt.setString(1, name);
        pstmt.setString(2, contactNo);
        pstmt.setString(3, address);
        pstmt.setString(4, email);
        pstmt.setString(5, password);

        int rowsInserted = pstmt.executeUpdate();
        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(this, "Dentist account created successfully!");
            clearFields();
            loadDentistDetails();
        }

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Database Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    



    
    
    }//GEN-LAST:event_CreateDAccountBtnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        
        int selectedRow = jTable1.getSelectedRow();
        
        if (selectedRow != -1) {
        // Set data to respective text fields based on column index
        DName.setText(model.getValueAt(selectedRow, 0).toString());
        DNo.setText(model.getValueAt(selectedRow, 1).toString());
        Daddress.setText(model.getValueAt(selectedRow, 2).toString());
        DEmail.setText(model.getValueAt(selectedRow, 3).toString());
        
        // Clear password fields for security reasons
        DPassword.setText("");
        ReDPassword.setText("");
    
}

        
    }//GEN-LAST:event_jTable1MouseClicked

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
      
    String name = DName.getText().trim();
    String contactNo = DNo.getText().trim();
    String address = Daddress.getText().trim();
    String email = DEmail.getText().trim();
    String password = new String(DPassword.getPassword());
    String rePassword = new String(ReDPassword.getPassword());

    // Validate if basic fields are empty
    if (name.isEmpty() || contactNo.isEmpty() || address.isEmpty() || email.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please select a record from the table to edit and fill all required fields.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    String sql;
    boolean updatePassword = false;

    // Check if user wants to update the password
    if (!password.isEmpty()) {
        if (!password.equals(rePassword)) {
            JOptionPane.showMessageDialog(this, "Passwords do not match!", "Password Mismatch", JOptionPane.WARNING_MESSAGE);
            return;
        }
        // Query to update all fields including password
        sql = "UPDATE dentist_details SET name=?, contact_no=?, address=?, password=? WHERE email=?";
        updatePassword = true;
    } else {
        // Query to update fields without changing the password
        sql = "UPDATE dentist_details SET name=?, contact_no=?, address=? WHERE email=?";
    }

    try (Connection conn = db.DBconnect.getConnection();
         PreparedStatement pstmt = conn.prepareStatement(sql)) {

        pstmt.setString(1, name);
        pstmt.setString(2, contactNo);
        pstmt.setString(3, address);

        if (updatePassword) {
            pstmt.setString(4, password);
            pstmt.setString(5, email);
        } else {
            pstmt.setString(4, email);
        }

        int rowsUpdated = pstmt.executeUpdate();
        if (rowsUpdated > 0) {
            JOptionPane.showMessageDialog(this, "Dentist account updated successfully!");
            clearFields();
            loadDentistDetails();
        } else {
            JOptionPane.showMessageDialog(this, "Update failed. Email address cannot be changed as it is used for identification.", "Update Error", JOptionPane.ERROR_MESSAGE);
        }

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Database Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_editBtnActionPerformed

    private void Searchbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Searchbtn1ActionPerformed
                                   
    String keyword = searchtxt.getText().trim();

    // Check if the search text field is empty
    if (keyword.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a keyword to search.", "Input Required", JOptionPane.WARNING_MESSAGE);
        loadDentistDetails(); // Load all data if search is empty
        return;
    }

    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    
    // Clear the table before displaying search results
    model.setRowCount(0); 

    // SQL query to search across all four columns using LIKE operator
    String sql = "SELECT name, contact_no, address, email FROM dentist_details WHERE name LIKE ? OR contact_no LIKE ? OR address LIKE ? OR email LIKE ?";

    try (Connection conn = db.DBconnect.getConnection();
         PreparedStatement pstmt = conn.prepareStatement(sql)) {

        // Add wildcards (%) to search for partial matches
        String searchPattern = "%" + keyword + "%";
        
        pstmt.setString(1, searchPattern);
        pstmt.setString(2, searchPattern);
        pstmt.setString(3, searchPattern);
        pstmt.setString(4, searchPattern);

        try (ResultSet rs = pstmt.executeQuery()) {
            boolean hasResults = false;
            
            // Iterate through the results and add to the table
            while (rs.next()) {
                hasResults = true;
                String name = rs.getString("name");
                String contact = rs.getString("contact_no");
                String address = rs.getString("address");
                String email = rs.getString("email");
                
                model.addRow(new Object[]{name, contact, address, email});
            }
            
            // Show a message if no matching records are found
            if (!hasResults) {
                JOptionPane.showMessageDialog(this, "No matching records found.", "Search Result", JOptionPane.INFORMATION_MESSAGE);
                loadDentistDetails(); // Reload original data
                searchtxt.setText(""); // Clear the text field
            }
        }

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Search Error: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_Searchbtn1ActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed

    searchtxt.setText("");
    
    // Reload all original data into the table
    loadDentistDetails();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        String name = DName.getText().trim();
        String contactNo = DNo.getText().trim();
        String address = Daddress.getText().trim();
        String email = DEmail.getText().trim();

        if (name.isEmpty() || contactNo.isEmpty() || address.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a record from the table to approve.", "Selection Required", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try (Connection conn = DBconnect.getConnection()) {

            // 1. Check if the dentist is already approved
            String checkSql = "SELECT COUNT(*) FROM approved_dentists WHERE email = ?";
            try (PreparedStatement checkStmt = conn.prepareStatement(checkSql)) {
                checkStmt.setString(1, email);
                try (ResultSet rs = checkStmt.executeQuery()) {
                    if (rs.next() && rs.getInt(1) > 0) {
                        JOptionPane.showMessageDialog(this, "This dentist has already been approved!", "Duplicate Entry", JOptionPane.WARNING_MESSAGE);
                        return; // Stop execution if already exists
                    }
                }
            }

            // 2. If not exists, proceed with the insertion
            String insertSql = "INSERT INTO approved_dentists (name, contact_no, address, email) VALUES (?, ?, ?, ?)";
            try (PreparedStatement insertStmt = conn.prepareStatement(insertSql)) {
                insertStmt.setString(1, name);
                insertStmt.setString(2, contactNo);
                insertStmt.setString(3, address);
                insertStmt.setString(4, email);

                int rowsInserted = insertStmt.executeUpdate();
                if (rowsInserted > 0) {
                    JOptionPane.showMessageDialog(this, "Dentist approved and saved successfully!");
                    clearFields();
                }
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_deleteBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selectedRow = jtable2.getSelectedRow();
    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a row to approve.");
        return;
    }
    
    try {
        DefaultTableModel dtm = (DefaultTableModel) jtable2.getModel();
        String workDate = dtm.getValueAt(selectedRow, 0).toString();
        String doctorName = dtm.getValueAt(selectedRow, 1).toString();
        String startTime = dtm.getValueAt(selectedRow, 2).toString();
        String endTime = dtm.getValueAt(selectedRow, 3).toString();
        
        Connection con = DBconnect.getConnection();
        
        // 1. Insert data into approved_dentist_schedule table
        java.sql.PreparedStatement pst = con.prepareStatement("INSERT INTO approved_dentist_schedule (work_date, doctor_name, start_time, end_time) VALUES (?, ?, ?, ?)");
        pst.setString(1, workDate);
        pst.setString(2, doctorName);
        pst.setString(3, startTime);
        pst.setString(4, endTime);
        pst.executeUpdate();
        
        // 2. Delete data from the original dentist table so it disappears from jtable2
        Statement st = con.createStatement();
        st.executeUpdate("DELETE FROM dentist WHERE doctor_name='" + doctorName + "' AND work_date='" + workDate + "' AND start_time='" + startTime + "'");
        
        JOptionPane.showMessageDialog(this, "Schedule approved successfully.");
        
        // 3. Refresh jtable2 to reflect the changes
        loadDentistSchedule();
        
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int selectedRow = jtable2.getSelectedRow();
    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a row to remove.");
        return;
    }
    
    try {
        DefaultTableModel dtm = (DefaultTableModel) jtable2.getModel();
        String doctorName = dtm.getValueAt(selectedRow, 1).toString();
        String workDate = dtm.getValueAt(selectedRow, 0).toString();
        
        Connection con = DBconnect.getConnection();
        Statement st = con.createStatement();
        st.executeUpdate("DELETE FROM dentist WHERE doctor_name='" + doctorName + "' AND work_date='" + workDate + "'");
        
        JOptionPane.showMessageDialog(this, "Record removed successfully.");
        loadDentistSchedule(); // Refresh table
        
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDentist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDentist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDentist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDentist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDentist().setVisible(true);
            }
        });
    }   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateDAccountBtn;
    private javax.swing.JTextField DEmail;
    private javax.swing.JTextField DName;
    private javax.swing.JTextField DNo;
    private javax.swing.JPasswordField DPassword;
    private javax.swing.JTextField Daddress;
    private javax.swing.JPasswordField ReDPassword;
    private javax.swing.JButton Searchbtn1;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jtable2;
    private javax.swing.JTextField searchtxt;
    // End of variables declaration//GEN-END:variables

    
}
