/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import db.DBconnect;

/**
 *
 * @author ashan
 */
public class LoginView extends javax.swing.JFrame {


    
    public LoginView() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Emailtxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Signupbtn = new javax.swing.JButton();
        pwstxt = new javax.swing.JPasswordField();
        signInbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("• Access bills and receipts");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("• Book appointments online");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("• View treatment history");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        jLabel6.setFont(new java.awt.Font("Poppins", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sunrise Dentali Clinic");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PATIENT SELF-SERVICE PORTAL");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Sunrise logo Light Small-01.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 710));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Poppins", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setText("Patient Sign In");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Access your appointments and dental records.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, -1, -1));

        jLabel8.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Email addess");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, -1, -1));

        Emailtxt.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        getContentPane().add(Emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 418, 39));

        jLabel9.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Password");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, -1, -1));

        jLabel10.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 204));
        jLabel10.setText("Forgot password?");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, -1, -1));

        Signupbtn.setBackground(new java.awt.Color(0, 153, 204));
        Signupbtn.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        Signupbtn.setForeground(new java.awt.Color(255, 255, 255));
        Signupbtn.setText("Sign Up");
        Signupbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Signupbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 30, 130, 45));

        pwstxt.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        getContentPane().add(pwstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 418, 39));

        signInbtn.setBackground(new java.awt.Color(0, 153, 204));
        signInbtn.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        signInbtn.setForeground(new java.awt.Color(255, 255, 255));
        signInbtn.setText("Sign In to Patient Portal");
        signInbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInbtnActionPerformed(evt);
            }
        });
        getContentPane().add(signInbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 322, 45));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SignupbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupbtnActionPerformed
        
    }//GEN-LAST:event_SignupbtnActionPerformed

    private void signInbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInbtnActionPerformed
        String email = Emailtxt.getText().trim();
    String password = new String(pwstxt.getPassword());

    if (email.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(
            this,
            "Please enter your email and password."
        );
        return;
    }

    String url = "jdbc:mysql://localhost:3306/dental_clinic_db";
    String username = "root";
    String dbPassword = "";

    try (Connection con = DriverManager.getConnection(
            url, username, dbPassword)) {

        // Check dentist login
        String dentistQuery =
                "SELECT name, email FROM dentist_details "
                + "WHERE email = ? AND password = ?";

        try (PreparedStatement pstDentist =
                     con.prepareStatement(dentistQuery)) {

            pstDentist.setString(1, email);
            pstDentist.setString(2, password);

            try (ResultSet rsDentist = pstDentist.executeQuery()) {

                if (rsDentist.next()) {
                    String dentistName =
                            rsDentist.getString("name");

                    String dentistEmail =
                            rsDentist.getString("email");

                    JOptionPane.showMessageDialog(
                        this,
                        "Dentist login successful!"
                    );

                    DentistUpdateView dentistDashboard =
                            new DentistUpdateView(
                                dentistName,
                                dentistEmail
                            );

                    dentistDashboard.setVisible(true);
                    this.dispose();
                    return;
                }
            }
        }

        // Check patient login
        String patientQuery =
        "SELECT patient_id, full_name, email "
        + "FROM patient_login "
        + "WHERE email = ? AND password = ?";

try (PreparedStatement pstPatient =
             con.prepareStatement(patientQuery)) {

    pstPatient.setString(1, email);
    pstPatient.setString(2, password);

    try (ResultSet rsPatient = pstPatient.executeQuery()) {

        if (rsPatient.next()) {

    int patientId =
            rsPatient.getInt("patient_id");

    String patientName =
            rsPatient.getString("full_name");

    JOptionPane.showMessageDialog(
            this,
            "Patient login successful!"
    );

    PatientDashboardView dashboard =
            new PatientDashboardView(
                    patientId,
                    patientName
            );

    dashboard.setVisible(true);
    this.dispose();
    return;
}
    }
}

        JOptionPane.showMessageDialog(
            this,
            "Incorrect email or password!",
            "Login Error",
            JOptionPane.ERROR_MESSAGE
        );

    } catch (SQLException e) {
        e.printStackTrace();

        JOptionPane.showMessageDialog(
            this,
            "Database Error: " + e.getMessage(),
            "Database Error",
            JOptionPane.ERROR_MESSAGE
        );
    }


    
    }//GEN-LAST:event_signInbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Emailtxt;
    private javax.swing.JButton Signupbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pwstxt;
    private javax.swing.JButton signInbtn;
    // End of variables declaration//GEN-END:variables
}
